/**
 * Direct port of `lib/core/utils/id_generator.dart`. Flutter generates a
 * plain UUID v4 (the `uuid` package's `Uuid().v4()`); `crypto.randomUUID()`
 * is the standard-library equivalent — RFC 4122 v4 — so IDs generated by
 * either app are the same format and never collide.
 */
export function generateId(): string {
  return crypto.randomUUID();
}
